### ISSUE TITLE
    raise CodegenError(f"Bad function prototype: {func[1]}") __main__.CodegenError: Bad function prototype: ['fprint', 'float']

### ISSUE THREAD

**Issue by adi-lb-phoenix** [chsasank/llama.lisp#40]
Command executed: 
``` 
guile ../../utils/sexp-json.scm < matrix_multiplication.sexp | python3 ../../c-lisp.py 
```
Output  received : 
```
Traceback (most recent call last):
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../c-lisp.py", line 430, in <module>
    json.dump(brilisp_code_generator.c_lisp(json.loads(sys.stdin.read())), sys.stdout)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../c-lisp.py", line 58, in c_lisp
    return ["brilisp"] + [self.gen_function(fn) for fn in prog[1:]]
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../c-lisp.py", line 58, in <listcomp>
    return ["brilisp"] + [self.gen_function(fn) for fn in prog[1:]]
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../c-lisp.py", line 78, in gen_function
    raise CodegenError(f"Bad function prototype: {func[1]}")
__main__.CodegenError: Bad function prototype: ['fprint', 'float']
```

This is the code that was written in c-lisp (matrix_multiplication.sexp):

```

(c-lisp

	(define (fprint float) ( n float))

 ;x is 10 , xout and w is 100 . d is 10 . n is 10
	(define ((mat_mul void) (xout (ptr float)) (x (ptr float)) (w (ptr float)) (n int) (d int)) 
		(declare (i int))
		(for ( (set i 0) (lt i d) (set i (add i 1)) )
			(declare (val float))
			(set val 0.0)
			(declare (j int))
			(for ((set j 0) (lt j n) (set j (add j 1)))
			   (set val (fadd val (fmul (load (ptradd w (add (mul i n) j))) (load (ptradd x j)))))
			)
			(store (ptradd xout i) val)
		) 
	)


	(define ((main void))
		(declare (xout (ptr float)))
		(declare (x (ptr float)))
		(declare (w (ptr float)))
		(declare (n int ))
		(declare (d int))


		(set xout (alloc float 100))
		(set x (alloc float 10))
		(set w (alloc float 100))
		(set n 10)
		(set d 10)
		(call print(call mat_mul xout x w n d))

	)
)

```

**Comment by GlowingScrewdriver** [comment]
Syntax for function definition requires that the entire function header (name, return type and parameters) are within a single list:
https://outline.von-neumann.ai/s/d0cd5eb9-2e15-4fa4-bd17-c3911f305008/doc/the-c-lisp-language-Ubb1ZvUrJs#h-functions

The correct way to write the definition for `fprint` is:
```
(define ((fprint float) ( n float)))
```
