### ISSUE TITLE
TypeError: Type of #1 arg mismatch: float != float* 

### ISSUE THREAD

**Issue by adi-lb-phoenix** [chsasank/llama.lisp#52]
command executed: 
```
guile ../../utils/sexp-json.scm < matrix_multiplication.sexp | python3 ../../c-lisp.py | python3 ../../brilisp.py |python3 ../../llvm.py 
``` 
the error occurs when the input is fed into llvm.py.

Output : 
```
tils/sexp-json.scm < matrix_multiplication.sexp | python3 ../../c-lisp.py | python3 ../../brilisp.py |python3 ../../llvm.py 
Exception: Type of #1 arg mismatch: float != float*; in instruction Munch({'op': 'call', 'type': 'float', 'dest': 'tmp_clisp-ppeutkft', 'funcs': ['fprint'], 'args': ['tmp_clisp-mdcdgkoo']}):
Traceback (most recent call last):
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../llvm.py", line 359, in <module>
    main()
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../llvm.py", line 354, in main
    code_gen.generate(bril_prog)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../llvm.py", line 44, in generate
    self.gen_function(fn)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../llvm.py", line 345, in gen_function
    self.gen_instructions(fn_instrs)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../llvm.py", line 261, in gen_instructions
    raise e
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../llvm.py", line 236, in gen_instructions
    gen_call(instr)
  File "/home/aadithya.bhat/c_lisp/bril/bril-txt/llama.lisp/src/backend/tests/llama2.c/../../llvm.py", line 143, in gen_call
    self.builder.call(callee_func, call_args, name=instr.dest),
  File "/home/aadithya.bhat/.local/lib/python3.10/site-packages/llvmlite/ir/builder.py", line 881, in call
    inst = instructions.CallInstr(self.block, fn, args, name=name,
  File "/home/aadithya.bhat/.local/lib/python3.10/site-packages/llvmlite/ir/instructions.py", line 105, in __init__
    raise TypeError(msg)
TypeError: Type of #1 arg mismatch: float != float*
```

This is the code that was written in c-lisp (matrix_multiplication.sexp) :
```

(c-lisp
	(define ((mat-cons void) (arr (ptr float)) (len int))
		(declare (n int))
		(declare (m float))
		(set m 71.5)
		(for ((set n 0) (lt n len) (set n (add n 1)) )
			(store (ptradd arr n) m )
		)
		(ret)
	)
	(define ((fprint float) (n  float) ))

	(define ((matmul_print void) (arr (ptr float)) (len int))
		(declare (i int))
		(for ((set i 0) (lt i len) (set i (add i 1))) 
			(call fprint (load (ptradd arr i)))
		)
		(ret) 
	) 


 ;x is 10 , xout and w is 100 . d is 10 . n is 10
	(define ((mat_mul void) (xout (ptr float)) (x (ptr float)) (w (ptr float)) (n int) (d int)) 
		(declare (i int))
		(for ( (set i 2) (lt i d) (set i (add i 1)) )
			(declare (val float))
			(set val 0.0)
			(declare (j int))
			(for ((set j 0) (lt j n) (set j (add j 1)))
			   (set val (fadd val (fmul (load (ptradd w (add (mul i n) j))) (load (ptradd x j)))))
			)
			(store (ptradd xout i) val)
		)
		(ret)  
	)


	(define ((main void))
		(declare (xout (ptr float)))
		(declare (x (ptr float)))
		(declare (w (ptr float)))
		(declare (n int ))
		(declare (d int))


		(set xout (alloc float 100))
		(set x (alloc float 10))
		(set w (alloc float 100))
		(set n 10)
		(set d 10)
		(call mat-cons w 100)
		(call mat-cons x 10)
		(call mat_mul xout x w n d)
		(call matmul_print xout 100)
		(call fprint xout)
		(ret) 
	)
)



```

**Comment by adi-lb-phoenix** [comment]
Needed to comment out the  he call to a function 
from 
```
(call fprint xout)
```
to 

```
;(call fprint xout)
```
as ```(define ((fprint float) (n  float) ))``` , does not  take a accept a pointer to a floating value rather a floating value itself. xout has been declared this way (declare (xout (ptr float))) .
if we wanted to use this statement (call fprint xout) , the make sure that xout is declared as a float variable and not float pointer.

**Comment by adi-lb-phoenix** [comment]
Observed this behavior in the output .
```
0.000000
0.000000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
-0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
-601984452337582034641557411575365632.000000
0.000000
0.000000
0.000000
0.000000
0.000000
74100848383122137433128304640.000000
0.000000
77119795884856424312856379392.000000
0.000000
0.000000
0.000000
0.000000
0.000000
-1.843628
0.000000
74100923940985863347451723776.000000
0.000000
0.000000
0.000000
0.000000
0.000000
-602147345439711362119649737937256448.000000
0.000000

```
